### PR TITLE
Lab3

### PR DESCRIPTION
**Pull request by ChoCoBo1712**

### CODE REVIEW

**Review by gmltA — CHANGES_REQUESTED** [review]
Please, assemble a signed release APK for me so I can test it.

**Comment by ChoCoBo1712** [comment]
@gmltA Here it is https://drive.google.com/file/d/1VSREpPpsmBfrRerBHu_kYmk_uOXX6ZE0/view?usp=sharing

**Comment by gmltA** [comment]
image

I think I have to ask you to send me a video of the game process.

**Comment by ChoCoBo1712** [comment]
Hmm, ok. Will do

**Comment by ChoCoBo1712** [comment]
@gmltA Here's a gameplay video https://drive.google.com/file/d/1b8T7HKerQWGpzUygGgmyKSvX8PvTLAu5/view?usp=sharing

**Review by gmltA — APPROVED** [review]
Tanks. Good luck.

**Pull request merged**
